#!/usr/bin/env python3
"""T4 GEO 落地页生成器（docs/PROJECT_PLAN.md §9-T4）。

输入：config/listings.yaml
输出：web/<sku>.html —— 自包含静态页（内联 CSS、零外链），含：
  - Product JSON-LD（价格/币种/库存/品牌，供 AI 购物助手与富摘要解析）
  - FAQPage JSON-LD
  - 「X vs 竞品」对比表（GEO 起手式：对比测评页）
  - 规格卖点区（语义化 HTML）
验收：JSON-LD 结构可被解析（tests 本地校验必填字段）；
      上线前用 Google Rich Results Test 复验（https://search.google.com/test/rich-results）。

用法：
    python3 tools/landing_page.py            # 生成全部 SKU 到 web/
    python3 tools/landing_page.py --out-dir /tmp/pages
"""

import argparse
import html
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_LISTINGS = ROOT / "config" / "listings.yaml"
DEFAULT_OUT = ROOT / "web"

CSS = """
:root{--ink:#1a1a1a;--paper:#fafaf7;--accent:#0a5c36;--line:#d9d9d2}
*{box-sizing:border-box;margin:0;padding:0}
body{font:16px/1.6 system-ui,-apple-system,sans-serif;color:var(--ink);background:var(--paper);max-width:860px;margin:0 auto;padding:24px}
header h1{font-size:1.7rem;line-height:1.25}
.tagline{color:var(--accent);font-weight:700;font-size:1.1rem;margin:.5rem 0}
.price{font-size:1.5rem;font-weight:800;margin:.6rem 0}
section{margin:2rem 0}
h2{font-size:1.2rem;border-bottom:2px solid var(--accent);padding-bottom:.3rem;margin-bottom:1rem}
ul.claims li{margin:.6rem 0 .6rem 1.2rem}
ul.claims .proof{color:#555;font-size:.92rem}
.tablewrap{overflow-x:auto}
table{border-collapse:collapse;width:100%;min-width:480px}
th,td{border:1px solid var(--line);padding:.55rem .7rem;text-align:left;vertical-align:top}
thead th{background:#efefe8}
td.us{background:#eaf4ee;font-weight:600}
dl.faq dt{font-weight:700;margin-top:1rem}
dl.faq dd{margin:.3rem 0 0 0}
footer{margin-top:3rem;padding-top:1rem;border-top:1px solid var(--line);font-size:.85rem;color:#666}
@media (prefers-color-scheme: dark){
 :root{--ink:#e8e8e3;--paper:#161614;--accent:#5dbb8a;--line:#3a3a35}
 thead th{background:#22221f} td.us{background:#1d2b23}
}
"""


def load_listings(path):
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def product_jsonld(sku, brand):
    return {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": sku["product_name"],
        "sku": sku["id"],
        "brand": {"@type": "Brand", "name": brand},
        "description": f"{sku['tagline']} {sku['fitment']}.",
        "offers": {
            "@type": "Offer",
            "price": f"{sku['price_aud']:.2f}",
            "priceCurrency": "AUD",
            "availability": "https://schema.org/InStock",
            "itemCondition": "https://schema.org/NewCondition",
            "shippingDetails": {
                "@type": "OfferShippingDetails",
                "shippingDestination": {"@type": "DefinedRegion", "addressCountry": "AU"},
                "deliveryTime": {
                    "@type": "ShippingDeliveryTime",
                    "transitTime": {"@type": "QuantitativeValue",
                                    "minValue": 7, "maxValue": 15, "unitCode": "DAY"},
                },
            },
        },
        "additionalProperty": [
            {"@type": "PropertyValue", "name": f"Feature {i}",
             "value": c["bullet"]} for i, c in enumerate(sku["claims"], 1)
        ],
    }


def faq_jsonld(sku):
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": f["q"],
             "acceptedAnswer": {"@type": "Answer", "text": f["a"]}}
            for f in sku.get("faq", [])
        ],
    }


def render_page(sku, listings):
    brand = listings["brand"]
    e = html.escape
    claims = "\n".join(
        f'      <li>{e(c["bullet"])}<br><span class="proof">{e(c["proof"])}</span></li>'
        for c in sku["claims"])
    comp = sku["comparison"]
    comp_rows = "\n".join(
        f'          <tr><th>{e(r["feature"])}</th><td class="us">{e(r["us"])}</td>'
        f'<td>{e(r["them"])}</td></tr>'
        for r in comp["rows"])
    faqs = "\n".join(
        f'      <dt>{e(f["q"])}</dt>\n      <dd>{e(f["a"])}</dd>'
        for f in sku.get("faq", []))
    jsonld_product = json.dumps(product_jsonld(sku, brand), ensure_ascii=False, indent=1)
    jsonld_faq = json.dumps(faq_jsonld(sku), ensure_ascii=False, indent=1)

    return f"""<!doctype html>
<!-- generated by tools/landing_page.py — edit config/listings.yaml, not this file -->
<html lang="en-AU">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{e(sku['product_name'])} — {e(brand)}</title>
<meta name="description" content="{e(sku['tagline'])} {e(sku['fitment'])}. A${sku['price_aud']}.">
<script type="application/ld+json">
{jsonld_product}
</script>
<script type="application/ld+json">
{jsonld_faq}
</script>
<style>{CSS}</style>
</head>
<body>
  <header>
    <h1>{e(sku['product_name'])}</h1>
    <p class="tagline">{e(sku['tagline'])}</p>
    <p>{e(sku['fitment'])}</p>
    <p class="price">A${sku['price_aud']}</p>
  </header>

  <section id="why">
    <h2>Why this one</h2>
    <ul class="claims">
{claims}
    </ul>
  </section>

  <section id="compare">
    <h2>{e(sku['product_name'])} vs {e(comp['rival'])}</h2>
    <div class="tablewrap">
      <table>
        <thead><tr><th>Feature</th><th>{e(brand)}</th><th>{e(comp['rival'])}</th></tr></thead>
        <tbody>
{comp_rows}
        </tbody>
      </table>
    </div>
  </section>

  <section id="faq">
    <h2>FAQ</h2>
    <dl class="faq">
{faqs}
    </dl>
  </section>

  <footer>
    <p>{e(listings['store_policy'])}</p>
    <p>Ships Australia-wide · 7–15 business days · GST included at checkout</p>
  </footer>
</body>
</html>
"""


def main(argv=None):
    ap = argparse.ArgumentParser(description="T4 GEO 落地页生成器")
    ap.add_argument("--listings", default=str(DEFAULT_LISTINGS))
    ap.add_argument("--out-dir", default=str(DEFAULT_OUT))
    args = ap.parse_args(argv)

    listings = load_listings(args.listings)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for sku in listings["skus"]:
        path = out_dir / f"{sku['id'].lower()}.html"
        path.write_text(render_page(sku, listings), encoding="utf-8")
        print(f"生成 {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
